name: Unit Tests

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux]

    services:
      # Label used to access the service container
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.5.10'
          cache: 'pip'
        env:
          PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
      - name: Install dependencies
        run: |
          sudo apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev node-less
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: python odoo-bin --test-enable -d test_db_1 --db_host localhost --db_pass postgres --stop-after-init
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

